"use client"

import "./globals.css";
import { AuthProvider, useAuthContext } from "@/context/AuthContext"; 
import type { Metadata } from "next";
import localFont from "next/font/local";
import React, { useEffect, useState } from "react";
import Navigation from "@/components/common/navbar";
import InfoPanel from "@/components/common/infoPanel";
import { DemoCreateAccountModal } from "@/components/common/modals/login";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function AuthContent({ children }: { children: React.ReactNode }) {
  const { isAuthenticated } = useAuthContext();

  return (
    <>
      {/* {!isAuthenticated && <DemoCreateAccountModal autoOpen={true} />} */}
      {children}
    </>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`dark antialiased`}>
        <AuthProvider>
          <AuthContent>
            <div className="flex justify-between h-screen bg-black text-white">
              <Navigation />
              {children}
              <InfoPanel />
            </div>
          </AuthContent>
        </AuthProvider>
      </body>
    </html>
  );
}