# Generated by Django 4.2.13 on 2024-10-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_picture',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
