# Generated by Django 4.2.13 on 2024-10-29 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profiles_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_handle',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Profile handle must be alphanumeric or contain underscores only.', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
