# Generated by Django 4.1.5 on 2024-10-28 17:31

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('artwork_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artwork_type', models.TextField(choices=[('image', 'By image'), ('video', 'By video'), ('model', 'By model')])),
                ('artwork_privacy', models.TextField(choices=[('public', 'Public'), ('private', 'Private')], default='public')),
                ('artwork_name', models.TextField(default='Untitled')),
                ('artwork_date', models.DateTimeField(blank=True, null=True)),
                ('artwork_images', models.JSONField(blank=True, default=dict)),
                ('artwork_location', models.TextField(blank=True)),
                ('artwork_dimensions', models.TextField(blank=True)),
                ('artwork_copyright', models.TextField(blank=True)),
                ('artwork_description', models.TextField(blank=True)),
                ('artwork_links', models.JSONField(blank=True, default=dict)),
                ('artwork_likes_counter', models.PositiveIntegerField(default=0)),
                ('artwork_comments_counter', models.PositiveIntegerField(default=0)),
                ('artwork_views_counter', models.PositiveIntegerField(default=0)),
                ('artwork_collections_counter', models.PositiveIntegerField(default=0)),
                ('artwork_shares_counter', models.PositiveIntegerField(default=0)),
                ('artwork_admin_list', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('artwork_superuser_list', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('artwork_creator_list', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('artwork_main_image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('artwork_main_image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('artwork_verification', models.BooleanField(default=True)),
            ],
        ),
    ]
