# Generated by Django 4.2.13 on 2024-10-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profiles_profile_picture'),
        ('artworks', '0002_remove_artworks_artwork_copyright_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworks',
            name='artwork_admin_list',
        ),
        migrations.AddField(
            model_name='artworks',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profiles'),
        ),
    ]
