# Generated by Django 4.2.13 on 2024-10-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_remove_artworks_artwork_admin_list_artworks_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworks',
            name='artwork_links',
        ),
    ]
