# Generated by Django 4.1.5 on 2024-11-08 12:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profiles_profile_handle'),
        ('artworks', '0004_remove_artworks_artwork_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworks',
            name='artwork_admin_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='ArtworkAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_artworks', to='users.profiles')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='artworks.artworks')),
            ],
            options={
                'unique_together': {('artwork', 'admin_user')},
            },
        ),
    ]
