# Generated by Django 4.2.13 on 2024-10-29 10:43

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('collection_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('collection_name', models.TextField()),
                ('collection_privacy', models.TextField(choices=[('public', 'Public'), ('private', 'Private')])),
                ('collection_type', models.TextField(choices=[('by_user', 'By User'), ('by_artist', 'By Artist'), ('by_institution', 'By Institution'), ('exhibition', 'Exhibition'), ('discover', 'Discover'), ('your_liked_artworks', 'Your Liked Artworks')], default='by_user')),
                ('collection_banner', models.TextField(blank=True, null=True)),
                ('collection_description', models.TextField(blank=True, null=True)),
                ('collection_likes_counter', models.IntegerField(default=0)),
                ('collection_artworks_counter', models.IntegerField(default=0)),
                ('collection_admin_list', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(blank=True), blank=True, default=list, size=None)),
                ('collection_images', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
